OPENAI_CHAT_API_KEY = "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"
OPENAI_CHAT_MODEL = "gpt-3.5-turbo"
# "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"
OPENAI_TEXT_MODEL = "text-davinci-003"
EVENT_EXT = "What is the event in this sentence? Define it with one word."
ARGUMENT_EXT = "This sentence describes an event. What arguments of this event are mentioned in this sentence? List them one by one concisely in format: \"argument type: argument content\""

PROMPT_0 = "Here are some examples of event arguments. Text and event arguments are provided. Each event argument consists of event argument type, event argument content, and event argument location. Event argument contents are quoted from the text. Event argument locations are the index or position of the first word of that event argument content in the text."
PROMPT_1 = "Based on the shown example above, extract the event arguments from the text below. The event argument types are given, please choose the appropriate phrase from the text to match each argument, and provide the location index of you choice. Remember that the number of argument contents are the same as the number of argument types that are provided, and each event argument location is the index or position of the first word of that event argument content in the text."
PROMPT_0_NL = "Here are some examples of event arguments. Text and event arguments are provided. Each event argument consists of event argument type and event argument content. Event argument contents are quoted from the text. Each event argument type match one and only one event argument content."
PROMPT_1_NL = "Based on the shown example above, extract the event arguments from the text below. The event argument types are given, please choose the appropriate phrase from the text to match each argument. Please only answer the given argument types Remember that the number of argument contents are the same as the number of argument types that are provided."
PROMPT_TEXT = "Text "
PROMPT_EVENT_TYPE = "Event type "
PROMPT_EVENT_ARGUMENT_TYPE = "Event argument types "
PROMPT_EVENT_ARGUMENT_CONTENT = "Event arguments contents "
PROMPT_EVENT_ARGUMENT_LOCATION = "Event argument locations "